global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # 从 Pushgateway 拉取 Collector 推送的指标
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  # Prometheus 自身监控
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
